service: WHATS-IN-MY-FRIDGE-api

frameworkVersion: "2"

provider:
    name: aws
    region: eu-west-2
    runtime: nodejs12.x
    lambdaHashingVersion: "20201221"

functions:
    hello:
        handler: src/handler.hello
        events:
            - http:
                  path: /
                  method: get
                  cors: true

    fetchItems:
        handler: src/items.fetchItems
        events:
            - http:
                  path: /items
                  method: get
                  cors: true
